In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
%xmode Plain

Exception reporting mode: Plain

In [2]:
import pandas as pd
import pycaret.classification as clf
import plotly.express as px

In [3]:
lending_data_raw_df = pd.read_csv("Loan_Default_Scoring_App\data_science_projects\Loan_Default_Scoring_App\data\lending_club.csv")

In [4]:
df = lending_data_raw_df

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9857 entries, 0 to 9856
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   funded_amnt                 9857 non-null   int64
 1   term                        9857 non-null   object
 2   int_rate                    9857 non-null   float64
 3   sub_grade                   9857 non-null   object
 4   addr_state                  9857 non-null   object
 5   verification_status         9857 non-null   object
 6   annual_inc                  9857 non-null   float64
 7   emp_length                  9857 non-null   object
 8   delinq_2yrs                 9857 non-null   int64
 9   inq_last_6mths              9857 non-null   int64
 10  revol_util                  9857 non-null   float64
 11  acc_now_delinq              9857 non-null   int64
 12  open_il_6m                  9857 non-null   int64
 13  open_il_12m                 9857 non-null   int64
 14  open_il_24m                 9857 non-null   int64
 15  total_bal_il                9857 non-null   int64
 16  all_util                    9857 non-null   int64
 17  inq_fi                      9857 non-null   int64
 18  inq_last_12m                9857 non-null   int64
 19  delinq_amnt                 9857 non-null   int64
 20  num_il_tl                   9857 non-null   int64
 21  total_il_high_credit_limit  9857 non-null   int64
 22  Class                       9857 non-null   object
dtypes: float64(3), int64(14), object(6)
memory usage: 1.7+ MB

In [6]:
float_cols = df.select_dtypes(include="float64").columns.to_list()

int_cols = df.select_dtypes(include="int64").columns.to_list()

numeric_columns = [*float_cols, *int_cols]

In [7]:
cat_columns = df.select_dtypes('object').drop("Class", axis=1).columns.to_list()

In [8]:
clf_1 = clf.setup(
    data       = df, 
    target     = "Class",
    train_size = 0.8,
    session_id = 123,
    
    categorical_features=cat_columns,
    numeric_features=numeric_columns
    
)

In [12]:
xgb_model = clf.create_model(
    estimator = 'xgboost'
)

IntProgress(value=0, description='Processing: ', max=4)

Initiated  . . . . . . . . . . . . . . . . . .                   02:28:53
Status     . . . . . . . . . . . . . . . . . .           Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Extreme Gradient Boosting

Empty DataFrame
Columns: [Fold, Accuracy, AUC, Recall, Prec., F1, Kappa, MCC]
Index: []

TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.